_target_: src.datagen.speech.generate

# sample rate [Hz]
fs: 16000
# segment duration in seconds
duration: 4
# train, valid, test
num_samps: [80000, 10000, 10000]
# snr range in dB
snr_range: [0, 60]
# path to rir data
rir_path: data/rirs_dataframe_curated_16k.pkl
# path to speech files
speech_path: ../data/speech/ears_dataset/
# filename of generated webdataset
out_path: data/dataset_speech/
# set false for dbg
write_flag: true

seed: 32

speech_representation:
  _target_: src.util.signals.MelSpectrogram
  sr: 16000
  n_fft: 64
  hop_size: 32
  n_mels: 16
  fmin: 20
  fmax: 8000
  power: 2.0
  log_mag: true
  trunc: 2000

rir_representation:
  _target_: src.util.signals.MelSpectrogram
  sr: 16000
  n_fft: 64
  hop_size: 16
  n_mels: 16
  fmin: 20
  fmax: 8000
  power: 2.0
  log_mag: true
  trunc: 1024