# @package _global_

defaults:
  - _self_
  - data: param_nb
  - model: param_nb
  - trainer: param_nb

# sets logging directory to debug
debug: false

target: edt
loss: l1

subdir: null

# hydra configuration
hydra:
  job:
    chdir: false
  run:
    dir: "."
  output_subdir: null
  job_logging:
    root: null
  sweep:
    dir: "."
    subdir: "." 