optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0003463830928347223
  weight_decay: 2.1389384493696443e-06

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.5
  patience: 20
  threshold: 0
  cooldown: 3
  min_lr: 1.0e-5

min_epochs: 1
max_epochs: 512
patience: 32