_target_: src.datagen.rirs.generate

# sample rate [Hz]
fs: 16000
# segment duration [s]
duration: 2
# train, valid, test
ratios: [0.7, 0.15, 0.15]
# path to rir data
rir_path: data/rirs_dataframe_curated_16k.pkl
# rir_path: data/measured_rirs_dataset.pkl
# filename of generated webdataset
out_path: data/dataset_rirs/
# set False for dbg
write_flag: true

seed: 32

rir_representation:
  _target_: src.util.signals.MelSpectrogram
  sr: 16000
  n_fft: 64
  hop_size: 16
  n_mels: 16
  fmin: 20
  fmax: 8000
  power: 2
  log_mag: true
  trunc: 1024
