# @package _global_

defaults:
  - _self_
  - data: vae
  - model: vae
  - trainer: vae

# sets logging directory to debug
debug: false

# hydra configuration
hydra:
  job:
    chdir: false
  run:
    dir: "."
  output_subdir: null
  job_logging:
    root: null
  sweep:
    dir: "."
    subdir: "." 