_target_: src.model.speech_encoder.SpeechEncoder
front_end:
  _target_: src.model.cnn2d.CNNEncoder
  in_channels: 1
  channels: 16
  multipliers: [1, 2, 2, 4, 4]
  kernel_sizes: [[1, 7], [1, 7], [3, 7], [3, 7], [3, 7]]
  strides: [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1]]
  factors: [[1, 1], [1, 2], [1, 2], [2, 2], [2, 2]]
  pads: [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
  num_blocks: [1, 1, 1, 1, 1]

sequence_model:
  _target_: src.model.seq.SequenceModel
  d_model: 256
  nhead: 4
  dim_feedforward: 512
  num_layers: 2
  dropout: 0.1
  d_out: 1024 # size of z_h
  act_out: tanh
  att_pool: true
  film: null

error_model:
  _target_: src.model.seq.SequenceModel
  d_model: 256
  nhead: 4
  dim_feedforward: 512
  num_layers: 1
  dropout: 0.1
  d_out: 32 # qlo, qhi (2 * n_mel)
  att_pool: false
  film:
    _target_: src.model.film.FiLMBlock
    num_features: 256
    latent_size: 1024

state: null