optimizer:
  _target_: torch.optim.AdamW
  lr: 0.00016
  weight_decay: 0.000652

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.5
  patience: 128

min_epochs: 1
max_epochs: 8192
patience: 256